// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_content_delivery_bucket": "coronavirux-prod",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "https://d2e92edyqo160s.cloudfront.net",
    "aws_appsync_graphqlEndpoint": "https://2sgz74cx2vdpddbyrmxzcv4beu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-4mjq4nnuqvcgdgb4efaajzg42u"
};


export default awsmobile;
